let g:coc_global_extensions = [
	\ 'coc-emmet',
	\ 'coc-explorer',
	\ 'coc-highlight',
	\ 'coc-markdownlint',
    \ 'coc-marketplace',
    \ 'coc-pyright',
	\ 'coc-python',
	\ 'coc-sh',
	\ 'coc-snippets',
	\ 'coc-sql',
	\ 'coc-yaml',
	\ 'coc-yank',
    \ 'coc-tsserver',
    \ 'coc-eslint',
    \ 'coc-vetur',
	\ ]
